name: Copilot Setup Steps

steps:
  - name: Setup Node
    uses: actions/setup-node@0a44ba7841725637a19e0b7ed9558ca7d829310b
    with:
      node-version: 22
      cache: npm

  - name: Install dependencies
    run: npm ci